language: python
python:
      - '3.9'

before_script:
      - pip install -r requirements.txt

branches:
    only:
      - stagging

env: DJANGO_SETTINGS_MODULE="django_web_app.settings.travis"

services:
      - postgresql

script:
      - python manage.py migrate
      - python manage.py test
      - ./manage.py test
