language: python
python:
      - '3.5'

before_script:
      - pip install -r requirements.txt

branches:
    only:
      - stagging

env: DJANGO_SETTINGS_MODULE="django_web_app.settings.travis"

services:
      - postgresql

script:
      - ./manage.py test
